DROP TABLE IF EXISTS employees;

CREATE TABLE employees (
  id INT PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  date_of_birth DATE(250) DEFAULT NULL,
  line1 VARCHAR(250) NOT NULL,
  line2 VARCHAR(250) NOT NULL,
  city VARCHAR(250) NOT NULL,
  country VARCHAR(250) NOT NULL,
  zip_code VARCHAR(250) NOT NULL
);